name: Update Holiday

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 60
          max_attempts: 3
          command: composer install --quiet --no-plugins --no-ansi --prefer-dist --no-progress --no-interaction

      - name: Update
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 60
          max_attempts: 3
          command: php bin/holiday-update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update Holiday
          delete-branch: true
          title: Update Holiday
          body: |
            Holiday have been updated.
