name: update

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '5.6'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Update
        run: php bin/holiday-update

      - name: Count changes
        id: changes
        run: |
          git add -N .
          echo "::set-output name=count::$(git diff --name-only | wc -l)"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update Holiday
          delete-branch: true
          title: Update Holiday
          body: |
            Holiday have been updated.
        if: ${{ steps.changes.outputs.count > 0 }}
